apiVersion: apps/v1
kind: Deployment
metadata:
  name: garethahealy
spec:
  selector:
    matchLabels:
      app: garethahealy
  replicas: 1
  template:
    metadata:
      labels:
        app: garethahealy
    spec:
      containers:
        - name: container
          imagePullPolicy: Always
          command:
            - sleep
            - '600'
          image: >-
            ghcr.io/garethahealy/verifying-redhat-images/example@sha256:0c397a050c90f13bdb18336d345df4188e70fac68008cd85a9fd59478ba15314
